# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kucun', '0001_initial'),
        ('jinhuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_id', models.CharField(default=0, max_length=20, unique=True, verbose_name='进货编号')),
                ('comedate', models.DateTimeField(default=datetime.datetime.now, verbose_name='进货日期')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Dept', verbose_name='进货部门')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Employee', verbose_name='验货人')),
            ],
            options={
                'verbose_name': '进货表',
                'verbose_name_plural': '进货表',
            },
        ),
        migrations.CreateModel(
            name='Buy_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='商品数量')),
                ('peice', models.IntegerField(default=0, verbose_name='商品进价(元)')),
                ('buy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoshou.Buy', verbose_name='进货编号')),
                ('buyorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.BuyOrder', verbose_name='采购合同')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Product', verbose_name='商品编号')),
            ],
            options={
                'verbose_name': '进货表明细',
                'verbose_name_plural': '进货表明细',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=0, max_length=20, unique=True, verbose_name='客户编号')),
                ('name', models.CharField(max_length=30, verbose_name='客户名称')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('phone', models.IntegerField(default=0, verbose_name='电话')),
                ('PostalCode', models.IntegerField(default=0, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(default=0, max_length=20, unique=True, verbose_name='销售编号')),
                ('saledate', models.DateTimeField(default=datetime.datetime.now, verbose_name='销售日期')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Dept', verbose_name='销售部门')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Employee', verbose_name='售货人')),
            ],
            options={
                'verbose_name': '销售表',
                'verbose_name_plural': '销售表',
            },
        ),
        migrations.CreateModel(
            name='Sale_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='商品数量')),
                ('peice', models.IntegerField(default=0, verbose_name='商品进价(元)')),
                ('discount', models.CharField(blank=True, max_length=20, null=True, verbose_name='折扣')),
            ],
            options={
                'verbose_name': '销售表明细',
                'verbose_name_plural': '销售表明细',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleorder_id', models.CharField(default=0, max_length=20, unique=True, verbose_name='合同编号')),
                ('writedate', models.DateTimeField(default=datetime.datetime.now, verbose_name='合同签订日期')),
                ('insuredate', models.DateTimeField(default=datetime.datetime.now, verbose_name='合同生效日期')),
                ('enddate', models.DateTimeField(default=datetime.datetime.now, verbose_name='合同到期日期')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Dept', verbose_name='签订部门')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Employee', verbose_name='合同主要负责人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoshou.Customer', verbose_name='客户编号')),
            ],
            options={
                'verbose_name': '销售合同表',
                'verbose_name_plural': '销售合同表',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='商品数量')),
                ('peice', models.IntegerField(default=0, verbose_name='商品进价(元)')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Product', verbose_name='销售商品编号')),
                ('saleorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoshou.SaleOrder', verbose_name='销售合同编号')),
            ],
            options={
                'verbose_name': '销售合同表明细',
                'verbose_name_plural': '销售合同表明细',
            },
        ),
        migrations.AddField(
            model_name='sale_detail',
            name='buyorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoshou.SaleOrder', verbose_name='销售合同'),
        ),
        migrations.AddField(
            model_name='sale_detail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Product', verbose_name='商品编号'),
        ),
        migrations.AddField(
            model_name='sale_detail',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoshou.Sale', verbose_name='销售编号'),
        ),
    ]
