# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jinhuo', '0001_initial'),
        ('kucun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstock',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jinhuo.Product', verbose_name='所退商品编号'),
        ),
    ]
